# Generated by Django 5.1.1 on 2024-09-16 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('gold_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
