# Generated by Django 5.1.1 on 2024-09-17 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_project_delete_moodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('gold_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=255)),
            ],
        ),
    ]
